//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int Id { get; set; }
        public string location_of_dispatch { get; set; }
        public string place_of_arrival { get; set; }
        public Nullable<System.DateTime> time_of_origin { get; set; }
        public Nullable<System.DateTime> arrival_time { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> class_of_service { get; set; }
    }
}
