//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Know
    {
        public int Id { get; set; }
        public string Knowledge { get; set; }
        public int confidence { get; set; }
        public int time { get; set; }
    }
}
