//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case1
{
    using System;
    using System.Collections.Generic;
    
    public partial class know2
    {
        public int Id { get; set; }
        public string condition { get; set; }
        public string rule { get; set; }
        public int time { get; set; }
    }
}
